In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
data_preprocessed=pd.read_csv('Absenteeism_preprocessed.csv')

In [3]:
data_preprocessed

,Reason 1,Reason 2,Reason 3,Reason 4,Month value,Day of week,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours
0,0,0,0,1,7,1,289,36,33,239.554,30,0,2,1,4
1,0,0,0,0,7,1,118,13,50,239.554,31,0,1,0,0
2,0,0,0,1,7,2,179,51,38,239.554,31,0,0,0,2
3,1,0,0,0,7,3,279,5,39,239.554,24,0,2,0,4
4,0,0,0,1,7,3,289,36,33,239.554,30,0,2,1,2
5,0,0,0,1,7,4,179,51,38,239.554,31,0,0,0,2
6,0,0,0,1,7,4,361,52,28,239.554,27,0,1,4,8
7,0,0,0,1,7,4,260,50,36,239.554,23,0,4,0,4
8,0,0,1,0,7,0,155,12,34,239.554,25,0,2,0,40
9,0,0,0,1,7,0,235,11,37,239.554,29,1,1,1,8
10,1,0,0,0,7,0,260,50,36,239.554,23,0,4,0,8
11,1,0,0,0,7,1,260,50,36,239.554,23,0,4,0,8
12,1,0,0,0,7,2,260,50,36,239.554,23,0,4,0,8
13,1,0,0,0,7,2,179,51,38,239.554,31,0,0,0,1
14,0,0,0,1,7,2,179,51,38,239.554,31,0,0,0,4
15,1,0,0,0,7,4,246,25,41,239.554,23,0,0,0,8
16,0,0,0,1,7,4,179,51,38,239.554,31,0,0,0,2
17,0,0,1,0,7,0,179,51,38,239.554,31,0,0,0,8
18,1,0,0,0,7,3,189,29,33,239.554,25,0,2,2,8
19,0,0,0,1,8,2,248,25,47,205.917,32,0,2,1,2
20,1,0,0,0,8,2,330,16,28,205.917,25,1,0,0,8
21,1,0,0,0,8,0,179,51,38,205.917,31,0,0,0,1
22,1,0,0,0,8,0,361,52,28,205.917,27,0,1,4,40
23,0,0,0,1,8,4,260,50,36,205.917,23,0,4,0,4
24,0,0,1,0,8,0,289,36,33,205.917,30,0,2,1,8
25,0,0,0,1,8,0,361,52,28,205.917,27,0,1,4,7
26,0,0,0,1,8,1,289,36,33,205.917,30,0,2,1,1
27,0,0,0,1,8,2,157,27,29,205.917,22,0,0,0,4
28,0,0,1,0,8,2,289,36,33,205.917,30,0,2,1,8
29,0,0,0,1,8,4,179,51,38,205.917,31,0,0,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
670,0,0,0,1,4,1,155,12,34,246.288,25,0,2,0,4
671,0,0,1,0,4,3,225,26,28,246.288,24,0,1,2,8
672,1,0,0,0,4,3,118,13,50,246.288,31,0,1,0,2
673,0,0,0,1,4,4,179,26,30,246.288,19,1,0,0,2
674,0,0,0,1,5,0,235,11,37,237.656,29,1,1,1,8
675,0,0,1,0,5,2,225,15,41,237.656,28,1,2,2,3
676,0,0,0,1,5,2,235,16,32,237.656,25,1,0,0,2
677,1,0,0,0,5,2,118,10,37,237.656,28,0,0,0,3
678,0,0,0,1,5,2,235,20,43,237.656,38,0,1,0,8
679,1,0,0,0,5,3,179,26,30,237.656,19,1,0,0,1
680,0,0,0,1,5,3,291,31,40,237.656,25,0,1,1,2
681,1,0,0,0,5,3,225,15,41,237.656,28,1,2,2,8
682,0,0,1,0,5,4,300,26,43,237.656,25,0,2,1,64
683,0,0,0,1,5,4,225,15,41,237.656,28,1,2,2,8
684,0,0,0,1,5,4,179,26,30,237.656,19,1,0,0,2
685,0,0,0,1,5,0,118,13,50,237.656,31,0,1,0,2
686,1,0,0,0,5,1,118,13,50,237.656,31,0,1,0,3
687,0,0,0,1,5,1,118,10,37,237.656,28,0,0,0,1
688,0,0,0,0,5,1,118,13,50,237.656,31,0,1,0,0
689,0,0,0,1,5,2,179,26,30,237.656,19,1,0,0,2
690,0,0,0,0,5,2,378,49,36,237.656,21,0,2,4,0
691,0,1,0,0,5,4,179,22,40,237.656,22,1,2,0,1
692,1,0,0,0,5,0,155,12,34,237.656,25,0,2,0,48
693,1,0,0,0,5,0,235,16,32,237.656,25,1,0,0,8
694,0,0,0,1,5,2,291,31,40,237.656,25,0,1,1,8
695,1,0,0,0,5,2,179,22,40,237.656,22,1,2,0,8
696,1,0,0,0,5,2,225,26,28,237.656,24,0,1,2,3
697,1,0,0,0,5,3,330,16,28,237.656,25,1,0,0,8
698,0,0,0,1,5,3,235,16,32,237.656,25,1,0,0,2
699,0,0,0,1,5,3,291,31,40,237.656,25,0,1,1,2

## CREATE TARGET

In [4]:
data_preprocessed['Absenteeism Time in Hours'].median()

3.0

##### moderately absent <=3 (0 value (target))
Excessively absent >=4 (1 value (target))

In [5]:
### np.where(expression>check,on_true,on_false)

In [6]:
targets=np.where(data_preprocessed["Absenteeism Time in Hours"]>3,1,0)

In [7]:
targets

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0])

In [8]:
#### using pandas it can be also done
targets=np.where(data_preprocessed["Absenteeism Time in Hours"]>data_preprocessed['Absenteeism Time in Hours'].median(),1,0)

In [9]:
targets

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0])

In [10]:
data_preprocessed['Excessive absenteeism']=targets

In [11]:
data_preprocessed.head()

,Reason 1,Reason 2,Reason 3,Reason 4,Month value,Day of week,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours,Excessive absenteeism
0,0,0,0,1,7,1,289,36,33,239.554,30,0,2,1,4,1
1,0,0,0,0,7,1,118,13,50,239.554,31,0,1,0,0,0
2,0,0,0,1,7,2,179,51,38,239.554,31,0,0,0,2,0
3,1,0,0,0,7,3,279,5,39,239.554,24,0,2,0,4,1
4,0,0,0,1,7,3,289,36,33,239.554,30,0,2,1,2,0

In [12]:
#around 45 percent data is of 1 and 55 percent is of 0
###target.sum gives 1
### target.shape[0] give 0 values
###### 60-40 ratio sould be there ideally
### but here 45-55 willalso work
targets.sum()/targets.shape[0]

0.45571428571428574

In [13]:
data_wiith_targets=data_preprocessed.drop(['Absenteeism Time in Hours','Day of week','Distance to Work','Daily Work Load Average'],axis=1)

##### data_wiith_targets is our check point

In [14]:
data_wiith_targets is data_preprocessed

False

In [15]:
data_wiith_targets.iloc[:,:14]

,Reason 1,Reason 2,Reason 3,Reason 4,Month value,Transportation Expense,Age,Body Mass Index,Education,Children,Pets,Excessive absenteeism
0,0,0,0,1,7,289,33,30,0,2,1,1
1,0,0,0,0,7,118,50,31,0,1,0,0
2,0,0,0,1,7,179,38,31,0,0,0,0
3,1,0,0,0,7,279,39,24,0,2,0,1
4,0,0,0,1,7,289,33,30,0,2,1,0
5,0,0,0,1,7,179,38,31,0,0,0,0
6,0,0,0,1,7,361,28,27,0,1,4,1
7,0,0,0,1,7,260,36,23,0,4,0,1
8,0,0,1,0,7,155,34,25,0,2,0,1
9,0,0,0,1,7,235,37,29,1,1,1,1
10,1,0,0,0,7,260,36,23,0,4,0,1
11,1,0,0,0,7,260,36,23,0,4,0,1
12,1,0,0,0,7,260,36,23,0,4,0,1
13,1,0,0,0,7,179,38,31,0,0,0,0
14,0,0,0,1,7,179,38,31,0,0,0,1
15,1,0,0,0,7,246,41,23,0,0,0,1
16,0,0,0,1,7,179,38,31,0,0,0,0
17,0,0,1,0,7,179,38,31,0,0,0,1
18,1,0,0,0,7,189,33,25,0,2,2,1
19,0,0,0,1,8,248,47,32,0,2,1,0
20,1,0,0,0,8,330,28,25,1,0,0,1
21,1,0,0,0,8,179,38,31,0,0,0,0
22,1,0,0,0,8,361,28,27,0,1,4,1
23,0,0,0,1,8,260,36,23,0,4,0,1
24,0,0,1,0,8,289,33,30,0,2,1,1
25,0,0,0,1,8,361,28,27,0,1,4,1
26,0,0,0,1,8,289,33,30,0,2,1,0
27,0,0,0,1,8,157,29,22,0,0,0,1
28,0,0,1,0,8,289,33,30,0,2,1,1
29,0,0,0,1,8,179,38,31,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
670,0,0,0,1,4,155,34,25,0,2,0,1
671,0,0,1,0,4,225,28,24,0,1,2,1
672,1,0,0,0,4,118,50,31,0,1,0,0
673,0,0,0,1,4,179,30,19,1,0,0,0
674,0,0,0,1,5,235,37,29,1,1,1,1
675,0,0,1,0,5,225,41,28,1,2,2,0
676,0,0,0,1,5,235,32,25,1,0,0,0
677,1,0,0,0,5,118,37,28,0,0,0,0
678,0,0,0,1,5,235,43,38,0,1,0,1
679,1,0,0,0,5,179,30,19,1,0,0,0
680,0,0,0,1,5,291,40,25,0,1,1,0
681,1,0,0,0,5,225,41,28,1,2,2,1
682,0,0,1,0,5,300,43,25,0,2,1,1
683,0,0,0,1,5,225,41,28,1,2,2,1
684,0,0,0,1,5,179,30,19,1,0,0,0
685,0,0,0,1,5,118,50,31,0,1,0,0
686,1,0,0,0,5,118,50,31,0,1,0,0
687,0,0,0,1,5,118,37,28,0,0,0,0
688,0,0,0,0,5,118,50,31,0,1,0,0
689,0,0,0,1,5,179,30,19,1,0,0,0
690,0,0,0,0,5,378,36,21,0,2,4,0
691,0,1,0,0,5,179,40,22,1,2,0,0
692,1,0,0,0,5,155,34,25,0,2,0,1
693,1,0,0,0,5,235,32,25,1,0,0,1
694,0,0,0,1,5,291,40,25,0,1,1,1
695,1,0,0,0,5,179,40,22,1,2,0,1
696,1,0,0,0,5,225,28,24,0,1,2,0
697,1,0,0,0,5,330,28,25,1,0,0,1
698,0,0,0,1,5,235,32,25,1,0,0,0
699,0,0,0,1,5,291,40,25,0,1,1,0

In [16]:
### more good way to select data
data_wiith_targets.iloc[:,:-1]

,Reason 1,Reason 2,Reason 3,Reason 4,Month value,Transportation Expense,Age,Body Mass Index,Education,Children,Pets
0,0,0,0,1,7,289,33,30,0,2,1
1,0,0,0,0,7,118,50,31,0,1,0
2,0,0,0,1,7,179,38,31,0,0,0
3,1,0,0,0,7,279,39,24,0,2,0
4,0,0,0,1,7,289,33,30,0,2,1
5,0,0,0,1,7,179,38,31,0,0,0
6,0,0,0,1,7,361,28,27,0,1,4
7,0,0,0,1,7,260,36,23,0,4,0
8,0,0,1,0,7,155,34,25,0,2,0
9,0,0,0,1,7,235,37,29,1,1,1
10,1,0,0,0,7,260,36,23,0,4,0
11,1,0,0,0,7,260,36,23,0,4,0
12,1,0,0,0,7,260,36,23,0,4,0
13,1,0,0,0,7,179,38,31,0,0,0
14,0,0,0,1,7,179,38,31,0,0,0
15,1,0,0,0,7,246,41,23,0,0,0
16,0,0,0,1,7,179,38,31,0,0,0
17,0,0,1,0,7,179,38,31,0,0,0
18,1,0,0,0,7,189,33,25,0,2,2
19,0,0,0,1,8,248,47,32,0,2,1
20,1,0,0,0,8,330,28,25,1,0,0
21,1,0,0,0,8,179,38,31,0,0,0
22,1,0,0,0,8,361,28,27,0,1,4
23,0,0,0,1,8,260,36,23,0,4,0
24,0,0,1,0,8,289,33,30,0,2,1
25,0,0,0,1,8,361,28,27,0,1,4
26,0,0,0,1,8,289,33,30,0,2,1
27,0,0,0,1,8,157,29,22,0,0,0
28,0,0,1,0,8,289,33,30,0,2,1
29,0,0,0,1,8,179,38,31,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...
670,0,0,0,1,4,155,34,25,0,2,0
671,0,0,1,0,4,225,28,24,0,1,2
672,1,0,0,0,4,118,50,31,0,1,0
673,0,0,0,1,4,179,30,19,1,0,0
674,0,0,0,1,5,235,37,29,1,1,1
675,0,0,1,0,5,225,41,28,1,2,2
676,0,0,0,1,5,235,32,25,1,0,0
677,1,0,0,0,5,118,37,28,0,0,0
678,0,0,0,1,5,235,43,38,0,1,0
679,1,0,0,0,5,179,30,19,1,0,0
680,0,0,0,1,5,291,40,25,0,1,1
681,1,0,0,0,5,225,41,28,1,2,2
682,0,0,1,0,5,300,43,25,0,2,1
683,0,0,0,1,5,225,41,28,1,2,2
684,0,0,0,1,5,179,30,19,1,0,0
685,0,0,0,1,5,118,50,31,0,1,0
686,1,0,0,0,5,118,50,31,0,1,0
687,0,0,0,1,5,118,37,28,0,0,0
688,0,0,0,0,5,118,50,31,0,1,0
689,0,0,0,1,5,179,30,19,1,0,0
690,0,0,0,0,5,378,36,21,0,2,4
691,0,1,0,0,5,179,40,22,1,2,0
692,1,0,0,0,5,155,34,25,0,2,0
693,1,0,0,0,5,235,32,25,1,0,0
694,0,0,0,1,5,291,40,25,0,1,1
695,1,0,0,0,5,179,40,22,1,2,0
696,1,0,0,0,5,225,28,24,0,1,2
697,1,0,0,0,5,330,28,25,1,0,0
698,0,0,0,1,5,235,32,25,1,0,0
699,0,0,0,1,5,291,40,25,0,1,1

In [17]:
unscaled_inputs=data_wiith_targets.iloc[:,:-1] ###DATAFRAME

##  STANDARDZE DATA

##### StandardScaler will used to subtract the mean and divide by std. devi. variablewise(featurewise)

In [18]:
#from sklearn.preprocessing import StandardScaler
#absenteeism_scaler=StandardScaler()

In [19]:
### we will only scale columns we want to scale
##hence ignoring dummy variable
## we have created this custom scaler as we have by mistake also scaled dummy variable which we should have not
##but thanks to the checkpoint we can use data from there (unscaled_inputs)
from sklearn.base import BaseEstimator,TransformerMixin
from sklearn.preprocessing import StandardScaler
class CustomScaler(BaseEstimator,TransformerMixin):
    def __init__(self,columns,copy=True,with_mean=True,with_std=True):
        self.scaler=StandardScaler(copy,with_mean,with_std)
        self.columns=columns
        self.mean_=None
        self.var_=None
    def fit(self,X,y=None):
        self.scaler.fit(X[self.columns])
        self.mean_=np.mean(X[self.columns])
        self.var_=np.var(X[self.columns])
        return self
    def transform(self,X,y=None,copy=None):
        init_col_order=X.columns
        X_scaled=pd.DataFrame(self.scaler.transform(X[self.columns]),columns=self.columns)
        X_not_scaled=X.loc[:,~X.columns.isin(self.columns)]
        return pd.concat([X_not_scaled,X_scaled],axis=1)[init_col_order]

In [20]:
unscaled_inputs.columns.values

array(['Reason 1', 'Reason 2', 'Reason 3', 'Reason 4', 'Month value',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children', 'Pets'], dtype=object)

In [21]:
#columns_to_scale=['Month value','Day of week', 'Transportation Expense', 'Distance to Work', 'Age','Daily Work Load Average', 'Body Mass Index','Children', 'Pets']
columns_to_omit=['Reason 1', 'Reason 2', 'Reason 3', 'Reason 4','Education']

In [22]:
columns_to_scale=[x for x in unscaled_inputs.columns.values if x not in columns_to_omit]

In [23]:
absenteeism_scaler=CustomScaler(columns_to_scale)

In [24]:
### ot will calculate and store mean and Std devia. from unscaled inputs featuewise
absenteeism_scaler.fit(unscaled_inputs)

CustomScaler(columns=['Month value', 'Transportation Expense', 'Age',
                      'Body Mass Index', 'Children', 'Pets'],
             copy=None, with_mean=None, with_std=None)

In [25]:
### to apply absenteesim scaler it uses data from absemt... to standardize unscaled_inputs
scaled_inputs=absenteeism_scaler.transform(unscaled_inputs)  ##ndARRAY

In [26]:
###alll data has been standardize
scaled_inputs

,Reason 1,Reason 2,Reason 3,Reason 4,Month value,Transportation Expense,Age,Body Mass Index,Education,Children,Pets
0,0,0,0,1,0.182726,1.005844,-0.536062,0.767431,0,0.880469,0.268487
1,0,0,0,0,0.182726,-1.574681,2.130803,1.002633,0,-0.019280,-0.589690
2,0,0,0,1,0.182726,-0.654143,0.248310,1.002633,0,-0.919030,-0.589690
3,1,0,0,0,0.182726,0.854936,0.405184,-0.643782,0,0.880469,-0.589690
4,0,0,0,1,0.182726,1.005844,-0.536062,0.767431,0,0.880469,0.268487
5,0,0,0,1,0.182726,-0.654143,0.248310,1.002633,0,-0.919030,-0.589690
6,0,0,0,1,0.182726,2.092381,-1.320435,0.061825,0,-0.019280,2.843016
7,0,0,0,1,0.182726,0.568211,-0.065439,-0.878984,0,2.679969,-0.589690
8,0,0,1,0,0.182726,-1.016322,-0.379188,-0.408580,0,0.880469,-0.589690
9,0,0,0,1,0.182726,0.190942,0.091435,0.532229,1,-0.019280,0.268487
10,1,0,0,0,0.182726,0.568211,-0.065439,-0.878984,0,2.679969,-0.589690
11,1,0,0,0,0.182726,0.568211,-0.065439,-0.878984,0,2.679969,-0.589690
12,1,0,0,0,0.182726,0.568211,-0.065439,-0.878984,0,2.679969,-0.589690
13,1,0,0,0,0.182726,-0.654143,0.248310,1.002633,0,-0.919030,-0.589690
14,0,0,0,1,0.182726,-0.654143,0.248310,1.002633,0,-0.919030,-0.589690
15,1,0,0,0,0.182726,0.356940,0.718933,-0.878984,0,-0.919030,-0.589690
16,0,0,0,1,0.182726,-0.654143,0.248310,1.002633,0,-0.919030,-0.589690
17,0,0,1,0,0.182726,-0.654143,0.248310,1.002633,0,-0.919030,-0.589690
18,1,0,0,0,0.182726,-0.503235,-0.536062,-0.408580,0,0.880469,1.126663
19,0,0,0,1,0.468236,0.387122,1.660180,1.237836,0,0.880469,0.268487
20,1,0,0,0,0.468236,1.624567,-1.320435,-0.408580,1,-0.919030,-0.589690
21,1,0,0,0,0.468236,-0.654143,0.248310,1.002633,0,-0.919030,-0.589690
22,1,0,0,0,0.468236,2.092381,-1.320435,0.061825,0,-0.019280,2.843016
23,0,0,0,1,0.468236,0.568211,-0.065439,-0.878984,0,2.679969,-0.589690
24,0,0,1,0,0.468236,1.005844,-0.536062,0.767431,0,0.880469,0.268487
25,0,0,0,1,0.468236,2.092381,-1.320435,0.061825,0,-0.019280,2.843016
26,0,0,0,1,0.468236,1.005844,-0.536062,0.767431,0,0.880469,0.268487
27,0,0,0,1,0.468236,-0.986140,-1.163560,-1.114186,0,-0.919030,-0.589690
28,0,0,1,0,0.468236,1.005844,-0.536062,0.767431,0,0.880469,0.268487
29,0,0,0,1,0.468236,-0.654143,0.248310,1.002633,0,-0.919030,-0.589690
...,...,...,...,...,...,...,...,...,...,...,...
670,0,0,0,1,-0.673803,-1.016322,-0.379188,-0.408580,0,0.880469,-0.589690
671,0,0,1,0,-0.673803,0.040034,-1.320435,-0.643782,0,-0.019280,1.126663
672,1,0,0,0,-0.673803,-1.574681,2.130803,1.002633,0,-0.019280,-0.589690
673,0,0,0,1,-0.673803,-0.654143,-1.006686,-1.819793,1,-0.919030,-0.589690
674,0,0,0,1,-0.388293,0.190942,0.091435,0.532229,1,-0.019280,0.268487
675,0,0,1,0,-0.388293,0.040034,0.718933,0.297027,1,0.880469,1.126663
676,0,0,0,1,-0.388293,0.190942,-0.692937,-0.408580,1,-0.919030,-0.589690
677,1,0,0,0,-0.388293,-1.574681,0.091435,0.297027,0,-0.919030,-0.589690
678,0,0,0,1,-0.388293,0.190942,1.032682,2.649049,0,-0.019280,-0.589690
679,1,0,0,0,-0.388293,-0.654143,-1.006686,-1.819793,1,-0.919030,-0.589690
680,0,0,0,1,-0.388293,1.036026,0.562059,-0.408580,0,-0.019280,0.268487
681,1,0,0,0,-0.388293,0.040034,0.718933,0.297027,1,0.880469,1.126663
682,0,0,1,0,-0.388293,1.171843,1.032682,-0.408580,0,0.880469,0.268487
683,0,0,0,1,-0.388293,0.040034,0.718933,0.297027,1,0.880469,1.126663
684,0,0,0,1,-0.388293,-0.654143,-1.006686,-1.819793,1,-0.919030,-0.589690
685,0,0,0,1,-0.388293,-1.574681,2.130803,1.002633,0,-0.019280,-0.589690
686,1,0,0,0,-0.388293,-1.574681,2.130803,1.002633,0,-0.019280,-0.589690
687,0,0,0,1,-0.388293,-1.574681,0.091435,0.297027,0,-0.919030,-0.589690
688,0,0,0,0,-0.388293,-1.574681,2.130803,1.002633,0,-0.019280,-0.589690
689,0,0,0,1,-0.388293,-0.654143,-1.006686,-1.819793,1,-0.919030,-0.589690
690,0,0,0,0,-0.388293,2.348925,-0.065439,-1.349389,0,0.880469,2.843016
691,0,1,0,0,-0.388293,-0.654143,0.562059,-1.114186,1,0.880469,-0.589690
692,1,0,0,0,-0.388293,-1.016322,-0.379188,-0.408580,0,0.880469,-0.589690
693,1,0,0,0,-0.388293,0.190942,-0.692937,-0.408580,1,-0.919030,-0.589690
694,0,0,0,1,-0.388293,1.036026,0.562059,-0.408580,0,-0.019280,0.268487
695,1,0,0,0,-0.388293,-0.654143,0.562059,-1.114186,1,0.880469,-0.589690
696,1,0,0,0,-0.388293,0.040034,-1.320435,-0.643782,0,-0.019280,1.126663
697,1,0,0,0,-0.388293,1.624567,-1.320435,-0.408580,1,-0.919030,-0.589690
698,0,0,0,1,-0.388293,0.190942,-0.692937,-0.408580,1,-0.919030,-0.589690
699,0,0,0,1,-0.388293,1.036026,0.562059,-0.408580,0,-0.019280,0.268487

In [27]:
scaled_inputs.shape

(700, 11)

## SPLIT DATA INTO TRAIN AND TEST

In [28]:
from sklearn.model_selection import train_test_split

array1 training data with i/p
array2 training data with target
array3 testing data with i/p
array4 testing data with target

train_test_split(i/p,target)

In [29]:
train_test_split(scaled_inputs,targets)

[     Reason 1  Reason 2  Reason 3  Reason 4  Month value  \
 4           0         0         0         1     0.182726
 512         0         0         0         1     1.039256
 474         0         0         0         1     0.182726
 579         0         0         1         0    -1.530333
 586         0         0         0         1    -1.244823
 133         0         0         0         1    -1.530333
 597         0         0         0         1    -1.244823
 395         0         0         0         1    -0.959313
 67          0         0         0         1     1.039256
 380         0         0         0         1    -1.244823
 252         0         0         1         0     0.468236
 31          0         0         1         0     0.468236
 130         0         0         1         0    -1.530333
 179         1         0         0         0    -0.959313
 162         1         0         0         0    -0.959313
 491         0         0         0         1     0.468236
 535         0         0         0         1     1.324766
 263         1         0         0         0     0.468236
 0           0         0         0         1     0.182726
 587         1         0         0         0    -1.244823
 119         0         0         0         1    -1.530333
 332         1         0         0         0     1.324766
 338         0         0         0         1     1.324766
 93          0         0         0         1     1.324766
 625         0         0         0         1    -0.959313
 121         0         0         0         1    -1.530333
 584         0         0         0         1    -1.530333
 450         0         0         0         1    -0.102784
 590         0         0         0         1    -1.244823
 435         0         0         0         1    -0.388293
 ..        ...       ...       ...       ...          ...
 521         1         0         0         0     1.039256
 197         0         0         1         0    -0.673803
 261         1         0         0         0     0.468236
 59          0         0         0         1     0.753746
 277         0         0         0         0     0.753746
 384         1         0         0         0    -1.244823
 402         0         0         0         1    -0.959313
 100         0         0         0         1     1.610276
 358         0         0         0         1    -1.530333
 589         0         0         0         1    -1.244823
 73          0         0         0         1     1.039256
 699         0         0         0         1    -0.388293
 319         1         0         0         0     1.324766
 456         0         0         1         0    -0.102784
 571         1         0         0         0    -1.530333
 543         1         0         0         0     1.324766
 124         0         0         0         1    -1.530333
 501         0         0         0         1     0.753746
 514         0         0         0         1     1.039256
 500         0         0         0         1     0.753746
 627         0         0         0         1    -0.959313
 105         0         0         0         1     1.610276
 370         0         0         0         1    -1.244823
 481         0         0         0         1     0.468236
 64          0         0         0         0     1.039256
 391         0         0         1         0    -0.959313
 166         0         0         0         1    -0.959313
 167         1         0         0         0    -0.959313
 190         0         0         0         1    -0.673803
 522         0         0         0         1     1.039256

      Transportation Expense       Age  Body Mass Index  Education  Children  \
 4                  1.005844 -0.536062         0.767431          0  0.880469
 512               -1.574681  0.091435         0.297027          0 -0.919030
 474                2.092381 -1.320435         0.061825          0 -0.019280
 579               -1.016322 -0.379188        -0.408580          0  0.880469
 586                0.040034 -1.320435        -0.643782          0 -0.019280
 133               -1.574681  0.091435         0.297027          0 -0.919030
 597               -0.654143  0.248310         1.002633          0 -0.919030
 395                0.190942  0.091435         0.532229          1 -0.019280
 67                 0.040034 -1.320435        -0.643782          0 -0.019280
 380               -0.503235 -0.536062        -0.408580          0  0.880469
 252                1.005844 -0.536062         0.767431          0  0.880469
 31                 0.190942  1.817054         1.473038          0 -0.019280
 130                1.005844 -0.536062         0.767431          0  0.880469
 179               -0.654143  0.248310         1.002633          0 -0.919030
 162                0.387122  1.660180         1.237836          0  0.880469
 491                0.356940  0.718933        -0.878984          0 -0.919030
 535               -0.654143  0.248310         1.002633          0 -0.919030
 263               -1.574681  2.130803         1.002633          0 -0.019280
 0                  1.005844 -0.536062         0.767431          0  0.880469
 587                0.387122  1.660180         1.237836          0  0.880469
 119                0.040034 -1.320435        -0.643782          0 -0.019280
 332                0.356940  0.718933        -0.878984          0 -0.919030
 338               -0.654143  0.248310         1.002633          0 -0.919030
 93                 0.568211 -0.065439        -0.878984          0  2.679969
 625               -0.654143  0.248310         1.002633          0 -0.919030
 121               -1.574681  0.091435         0.297027          0 -0.919030
 584               -0.654143  0.248310         1.002633          0 -0.919030
 450               -0.654143  0.248310         1.002633          0 -0.919030
 590               -0.654143  0.248310         1.002633          0 -0.919030
 435                0.040034 -1.320435        -0.643782          0 -0.019280
 ..                      ...       ...              ...        ...       ...
 521                0.085306  3.385799        -1.114186          0  0.880469
 197                0.568211 -0.065439        -0.878984          0  2.679969
 261                0.688938 -0.536062        -0.408580          1 -0.919030
 59                 0.387122  1.660180         1.237836          0  0.880469
 277                1.036026 -0.692937        -0.878984          0 -0.919030
 384               -0.986140 -1.163560        -1.114186          0 -0.919030
 402               -1.574681  2.130803         1.002633          0 -0.019280
 100               -1.574681  2.130803         1.002633          0 -0.019280
 358                0.040034 -1.320435        -0.643782          0 -0.019280
 589                0.040034 -1.320435        -0.643782          0 -0.019280
 73                 0.040034 -1.320435        -0.643782          0 -0.019280
 699                1.036026  0.562059        -0.408580          0 -0.019280
 319               -0.654143  0.248310         1.002633          0 -0.919030
 456               -0.654143 -1.006686        -1.819793          1 -0.919030
 571               -0.654143 -1.006686        -1.819793          1 -0.919030
 543                0.040034 -1.320435        -0.643782          0 -0.019280
 124               -1.574681  0.091435         0.297027          0 -0.919030
 501                0.387122  1.660180         1.237836          0  0.880469
 514                1.036026  0.562059        -0.408580          0 -0.019280
 500               -0.654143 -1.006686        -1.819793          1 -0.919030
 627               -0.654143 -1.006686        -1.819793          1 -0.919030
 105                2.092381 -1.320435         0.061825          0 -0.019280
 370               -0.654143  0.248310         1.002633          0 -0.919030
 481               -0.654143  0.562059        -1.114186          1  0.880469
 64                -1.574681  2.130803         1.002633          0 -0.019280
 391                0.356940  0.718933        -0.878984          0 -0.919030
 166                0.568211 -0.065439        -0.878984          0  2.679969
 167               -1.016322 -0.379188        -0.408580          0  0.880469
 190                0.568211 -0.065439        -0.878984          0  2.679969
 522                1.036026  0.562059        -0.408580          0 -0.019280

          Pets
 4    0.268487
 512 -0.589690
 474  2.843016
 579 -0.589690
 586  1.126663
 133 -0.589690
 597 -0.589690
 395  0.268487
 67   1.126663
 380  1.126663
 252  0.268487
 31   3.701192
 130  0.268487
 179 -0.589690
 162  0.268487
 491 -0.589690
 535 -0.589690
 263 -0.589690
 0    0.268487
 587  0.268487
 119  1.126663
 332 -0.589690
 338 -0.589690
 93  -0.589690
 625 -0.589690
 121 -0.589690
 584 -0.589690
 450 -0.589690
 590 -0.589690
 435  1.126663
 ..        ...
 521  0.268487
 197 -0.589690
 261 -0.589690
 59   0.268487
 277 -0.589690
 384 -0.589690
 402 -0.589690
 100 -0.589690
 358  1.126663
 589  1.126663
 73   1.126663
 699  0.268487
 319 -0.589690
 456 -0.589690
 571 -0.589690
 543  1.126663
 124 -0.589690
 501  0.268487
 514  0.268487
 500 -0.589690
 627 -0.589690
 105  2.843016
 370 -0.589690
 481 -0.589690
 64  -0.589690
 391 -0.589690
 166 -0.589690
 167 -0.589690
 190 -0.589690
 522  0.268487

 [525 rows x 11 columns],
      Reason 1  Reason 2  Reason 3  Reason 4  Month value  \
 256         1         0         0         0     0.468236
 219         0         0         0         1    -0.388293
 335         0         1         0         0     1.324766
 551         0         0         0         0     1.324766
 208         0         0         1         0    -0.388293
 201         1         0         0         0    -0.673803
 503         0         0         0         1     0.753746
 131         0         0         0         1    -1.530333
 645         0         0         0         1    -0.959313
 340         0         0         0         1     1.610276
 171         0         0         0         1    -0.959313
 698         0         0         0         1    -0.388293
 441         0         0         0         1    -0.102784
 149         0         0         0         1    -1.244823
 147         0         0         0         1    -1.244823
 3           1         0         0         0     0.182726
 511         0         0         0         1     1.039256
 404         1         0         0         0    -0.959313
 21          1         0         0         0     0.468236
 36          0         0         0         1     0.468236
 324         0         0         0         1     1.324766
 345         1         0         0         0     1.610276
 87          1         0         0         0     1.324766
 563         0         0         0         1     1.610276
 174         0         0         0         1    -0.959313
 192         0         0         0         1    -0.673803
 483         0         0         0         1     0.468236
 582         1         0         0         0    -1.530333
 448         0         0         0         1    -0.102784
 126         0         0         0         1    -1.530333
 ..        ...       ...       ...       ...          ...
 109         0         0         0         1     1.610276
 9           0         0         0         1     0.182726
 674         0         0         0         1    -0.388293
 489         0         0         0         1     0.468236
 679         1         0         0         0    -0.388293
 16          0         0         0         1     0.182726
 359         0         0         1         0    -1.530333
 127         0         0         0         1    -1.530333
 58          0         0         0         0     0.753746
 318         0         0         0         1     1.324766
 555         1         0         0         0     1.610276
 181         0         0         0         1    -0.959313
 383         0         0         0         1    -1.244823
 612         0         0         0         1    -1.244823
 695         1         0         0         0    -0.388293
 10          1         0         0         0     0.182726
 90          0         0         0         1     1.324766
 170         0         0         0         1    -0.959313
 42          0         0         0         1     0.753746
 673         0         0         0         1    -0.673803
 661         0         1         0         0    -0.673803
 605         0         0         0         1    -1.244823
 678         0         0         0         1    -0.388293
 451         0         0         0         1    -0.102784
 670         0         0         0         1    -0.673803
 659         0         0         0         1    -0.673803
 85          1         0         0         0     1.324766
 159         0         0         0         1    -0.959313
 169         1         0         0         0    -0.959313
 212         1         0         0         0    -0.388293

      Transportation Expense       Age  Body Mass Index  Education  Children  \
 256                1.171843  1.032682        -0.408580          0  0.880469
 219                2.092381 -1.320435         0.061825          0 -0.019280
 335                0.568211 -0.065439        -0.878984          0  2.679969
 551                0.190942  1.032682         2.649049          0 -0.019280
 208                0.040034 -1.320435        -0.643782          0 -0.019280
 201                1.005844 -0.536062         0.767431          0  0.880469
 503                0.040034 -1.320435        -0.643782          0 -0.019280
 131               -1.574681  0.091435         0.297027          0 -0.919030
 645               -0.654143  0.248310         1.002633          0 -0.919030
 340               -0.654143  0.248310         1.002633          0 -0.919030
 171                0.040034 -1.320435        -0.643782          0 -0.019280
 698                0.190942 -0.692937        -0.408580          1 -0.919030
 441               -1.574681  0.091435         0.297027          0 -0.919030
 149               -0.578689 -1.477309        -1.349389          0 -0.919030
 147                0.040034 -1.320435        -0.643782          0 -0.019280
 3                  0.854936  0.405184        -0.643782          0  0.880469
 511                1.036026  0.562059        -0.408580          0 -0.019280
 404               -1.574681  2.130803         1.002633          0 -0.019280
 21                -0.654143  0.248310         1.002633          0 -0.919030
 36                 1.005844 -0.536062         0.767431          0  0.880469
 324                0.190942  1.032682         2.649049          0 -0.019280
 345                0.356940  0.718933        -0.878984          0 -0.919030
 87                 1.036026  0.562059        -0.408580          0 -0.019280
 563                0.190942  1.032682         2.649049          0 -0.019280
 174                0.040034 -1.320435        -0.643782          0 -0.019280
 192               -1.574681  2.130803         1.002633          0 -0.019280
 483               -1.574681  0.091435         0.297027          0 -0.919030
 582                1.005844 -0.536062         0.767431          0  0.880469
 448               -0.654143  0.248310         1.002633          0 -0.919030
 126               -1.574681  0.091435         0.297027          0 -0.919030
 ..                      ...       ...              ...        ...       ...
 109                2.092381 -1.320435         0.061825          0 -0.019280
 9                  0.190942  0.091435         0.532229          1 -0.019280
 674                0.190942  0.091435         0.532229          1 -0.019280
 489                1.624567 -1.320435        -0.408580          1 -0.919030
 679               -0.654143 -1.006686        -1.819793          1 -0.919030
 16                -0.654143  0.248310         1.002633          0 -0.919030
 359               -1.574681  0.091435         0.297027          0 -0.919030
 127               -1.574681  0.091435         0.297027          0 -0.919030
 58                 2.213108 -0.849811        -0.408580          0  1.780219
 318                0.387122  1.660180         1.237836          0  0.880469
 555               -0.654143  0.248310         1.002633          0 -0.919030
 181                0.040034 -1.320435        -0.643782          0 -0.019280
 383                1.036026  0.562059        -0.408580          0 -0.019280
 612               -0.654143  0.248310         1.002633          0 -0.919030
 695               -0.654143  0.562059        -1.114186          1  0.880469
 10                 0.568211 -0.065439        -0.878984          0  2.679969
 90                 0.040034 -1.320435        -0.643782          0 -0.019280
 170                0.568211 -0.065439        -0.878984          0  2.679969
 42                -0.654143  0.248310         1.002633          0 -0.919030
 673               -0.654143 -1.006686        -1.819793          1 -0.919030
 661               -0.654143  0.562059        -1.114186          1  0.880469
 605               -0.654143  0.248310         1.002633          0 -0.919030
 678                0.190942  1.032682         2.649049          0 -0.019280
 451                0.190942  1.032682         2.649049          0 -0.019280
 670               -1.016322 -0.379188        -0.408580          0  0.880469
 659               -0.654143 -1.006686        -1.819793          1 -0.919030
 85                -1.016322 -0.379188        -0.408580          0  0.880469
 159                1.036026  0.562059        -0.408580          0 -0.019280
 169               -0.654143  0.562059        -1.114186          1  0.880469
 212                1.005844 -0.536062         0.767431          0  0.880469

          Pets
 256  0.268487
 219  2.843016
 335 -0.589690
 551 -0.589690
 208  1.126663
 201  0.268487
 503  1.126663
 131 -0.589690
 645 -0.589690
 340 -0.589690
 171  1.126663
 698 -0.589690
 441 -0.589690
 149 -0.589690
 147  1.126663
 3   -0.589690
 511  0.268487
 404 -0.589690
 21  -0.589690
 36   0.268487
 324 -0.589690
 345 -0.589690
 87   0.268487
 563 -0.589690
 174  1.126663
 192 -0.589690
 483 -0.589690
 582  0.268487
 448 -0.589690
 126 -0.589690
 ..        ...
 109  2.843016
 9    0.268487
 674  0.268487
 489 -0.589690
 679 -0.589690
 16  -0.589690
 359 -0.589690
 127 -0.589690
 58  -0.589690
 318  0.268487
 555 -0.589690
 181  1.126663
 383  0.268487
 612 -0.589690
 695 -0.589690
 10  -0.589690
 90   1.126663
 170 -0.589690
 42  -0.589690
 673 -0.589690
 661 -0.589690
 605 -0.589690
 678 -0.589690
 451 -0.589690
 670 -0.589690
 659 -0.589690
 85  -0.589690
 159  0.268487
 169 -0.589690
 212  0.268487

 [175 rows x 11 columns],
 array([0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1,
        0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0,
        0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1,
        1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1,
        0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1,
        0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
        0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1,
        0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0,
        0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0,
        1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0,
        0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1,
        0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0,
        1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1,
        1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1,
        0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0,
        1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,

###### train_test_split(scaled_inputs,targets,train_size=0.8) means trainig wil be done on 80% and 20% will be testing data

In [30]:
x_train,x_test,y_train,y_test=train_test_split(scaled_inputs,targets,train_size=0.8,random_state=20)

x_train contain 525 with 14 feature(excessive absenteeism)
y_train contain 525 without 14 feature(excessive absenteeism)

In [31]:
print(x_train.shape,y_train.shape) ##75%

(560, 11) (560,)

x_test contain 525 with 14 feature(excessive absenteeism)
y_test contain 525 without 14 feature(excessive absenteeism)

In [32]:
print(x_test.shape,y_test.shape)  ##25

(140, 11) (140,)

## LOGISTIC REGRESSION

In [33]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

In [34]:
reg=LogisticRegression()

In [35]:
reg.fit(x_train,y_train)

C:\Users\rana\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [36]:
reg.score(x_train,y_train)

0.775

MANUALLY CHECKING THE SCORE

In [37]:
model_outputs=reg.predict(x_train)

In [38]:
model_outputs.shape

(560,)

In [39]:
model_outputs

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0,
       1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 1, 1, 1, 0, 0, 0, 0])

In [40]:
y_train

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1,
       1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0])

In [41]:
model_outputs==y_train

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True, False, False,  True,  True,  True,  True,
       False,  True, False,  True, False, False,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False, False, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
       False,  True, False,  True,  True, False, False, False,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
       False,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True,  True, False,
        True, False,  True, False,  True,  True,  True,  True, False,
       False, False,  True,  True, False,  True, False,  True,  True,
        True, False,  True, False,  True, False,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True, False,
       False,  True,  True,  True,  True,  True,  True,  True, False,
        True, False,  True, False,  True,  True,  True,  True, False,
        True, False, False,  True,  True,  True,  True,  True, False,
       False, False,  True, False,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
        True, False, False,  True,  True,  True,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True, False, False,
       False,  True,  True,  True,  True, False,  True, False,  True,
        True,  True,  True,  True,  True,  True, False,  True, False,
       False,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True, False, False,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True, False,
       False,  True,  True,  True,  True,  True, False,  True, False,
        True,  True,  True, False, False,  True,  True,  True, False,
        True, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
       False,  True,  True, False,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True, False,  True,  True,  True, False,  True,
        True, False,  True, False,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
       False,  True,  True, False,  True, False,  True,  True,  True,
        True,  True,  True, False,  True,  True, False,  True, False,
        True,  True,  True,  True,  True, False, False,  True,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
       False,  True,  True,  True, False, False,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True, False,  True,  True, False, False,  True,  True,
       False,  True,  True,  True,  True,  True,  True, False, False,
        True,  True, False,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
        True, False,  True,  True, False, False,  True,  True,  True,
       False,  True,  True,  True,  True,  True, False,  True,  True,
       False, False, False,  True,  True, False,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True, False,  True,  True,  True,  True, False,  True,
       False,  True])

true =1
false=0
sum will be equal to total entry of true

In [42]:
np.sum((model_outputs==y_train))

434

Accuracy=correct prediction/#observations

In [43]:
### we can see sklear and manual accuracy is same
np.sum((model_outputs==y_train))/model_outputs.shape[0]

0.775

## FINDING INTERCEPT AND COFFICIENTS

In [44]:
reg.intercept_

array([-1.46547112])

In [45]:
reg.coef_

array([[ 2.62749942,  0.86338637,  2.96050661,  0.66390745,  0.15493732,
         0.59979822, -0.17245127,  0.27568526, -0.23452541,  0.34249662,
        -0.2775137 ]])

##  WHENEVER WE EMPLOY SKLEARN USUALLY THE RESILTS ARE IN NDARRAY NOT IN DATAFRAME

In [46]:
scaled_inputs.columns.values

array(['Reason 1', 'Reason 2', 'Reason 3', 'Reason 4', 'Month value',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children', 'Pets'], dtype=object)

In [47]:
unscaled_inputs.columns.values

array(['Reason 1', 'Reason 2', 'Reason 3', 'Reason 4', 'Month value',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children', 'Pets'], dtype=object)

In [48]:
feature_name=unscaled_inputs.columns.values

In [49]:
summary_table=pd.DataFrame(columns=["Feature names"],data=feature_name)
summary_table["Cofficient"]=np.transpose(reg.coef_) ### we have to transpose as nd arrays are roes not columns

In [50]:
summary_table

             Feature names  Cofficient
0                 Reason 1    2.627499
1                 Reason 2    0.863386
2                 Reason 3    2.960507
3                 Reason 4    0.663907
4              Month value    0.154937
5   Transportation Expense    0.599798
6                      Age   -0.172451
7          Body Mass Index    0.275685
8                Education   -0.234525
9                 Children    0.342497
10                    Pets   -0.277514

In [51]:
summary_table.index=summary_table.index+1 ## it will shift all table by 1
summary_table.loc[0]=["Intercept",reg.intercept_[0]] ## 0 so we can extract the no 
summary_table=summary_table.sort_index()

In [52]:
## if you want to delete specific row summary_table.drop(summary_table.index[1])
# summary_table=summary_table.drop(summary_table.index[1]) ##glti se 2 baar insert ho gya tha intercept

In [53]:
summary_table

             Feature names  Cofficient
0                Intercept   -1.465471
1                 Reason 1    2.627499
2                 Reason 2    0.863386
3                 Reason 3    2.960507
4                 Reason 4    0.663907
5              Month value    0.154937
6   Transportation Expense    0.599798
7                      Age   -0.172451
8          Body Mass Index    0.275685
9                Education   -0.234525
10                Children    0.342497
11                    Pets   -0.277514

##  INTERPRETTING THE COFFICIENT

In [54]:
summary_table["odds ratio"]=np.exp(summary_table.Cofficient)

In [55]:
summary_table

             Feature names  Cofficient  odds ratio
0                Intercept   -1.465471    0.230969
1                 Reason 1    2.627499   13.839121
2                 Reason 2    0.863386    2.371177
3                 Reason 3    2.960507   19.307751
4                 Reason 4    0.663907    1.942367
5              Month value    0.154937    1.167585
6   Transportation Expense    0.599798    1.821751
7                      Age   -0.172451    0.841599
8          Body Mass Index    0.275685    1.317433
9                Education   -0.234525    0.790946
10                Children    0.342497    1.408460
11                    Pets   -0.277514    0.757665

In [56]:
summary_table.sort_values("odds ratio",ascending=False)

             Feature names  Cofficient  odds ratio
3                 Reason 3    2.960507   19.307751
1                 Reason 1    2.627499   13.839121
2                 Reason 2    0.863386    2.371177
4                 Reason 4    0.663907    1.942367
6   Transportation Expense    0.599798    1.821751
10                Children    0.342497    1.408460
8          Body Mass Index    0.275685    1.317433
5              Month value    0.154937    1.167585
7                      Age   -0.172451    0.841599
9                Education   -0.234525    0.790946
11                    Pets   -0.277514    0.757665
0                Intercept   -1.465471    0.230969

##  TESTING THE MODEL

In [57]:
reg.score(x_test,y_test)

0.75

In [59]:
predicted_proba=reg.predict_proba(x_test)
predicted_proba
##prob of [0,1]

array([[0.71221976, 0.28778024],
       [0.58760009, 0.41239991],
       [0.44337438, 0.55662562],
       [0.77903962, 0.22096038],
       [0.08458343, 0.91541657],
       [0.33103371, 0.66896629],
       [0.29792496, 0.70207504],
       [0.12956221, 0.87043779],
       [0.78307821, 0.21692179],
       [0.74708659, 0.25291341],
       [0.49514969, 0.50485031],
       [0.22640297, 0.77359703],
       [0.07030984, 0.92969016],
       [0.73504052, 0.26495948],
       [0.30533085, 0.69466915],
       [0.55035881, 0.44964119],
       [0.55027426, 0.44972574],
       [0.53930442, 0.46069558],
       [0.40117774, 0.59882226],
       [0.05320682, 0.94679318],
       [0.69874615, 0.30125385],
       [0.77903962, 0.22096038],
       [0.41634563, 0.58365437],
       [0.41634563, 0.58365437],
       [0.2412915 , 0.7587085 ],
       [0.74317087, 0.25682913],
       [0.51065194, 0.48934806],
       [0.85703303, 0.14296697],
       [0.19934235, 0.80065765],
       [0.77903962, 0.22096038],
       [0.62971577, 0.37028423],
       [0.31683213, 0.68316787],
       [0.31174245, 0.68825755],
       [0.47305759, 0.52694241],
       [0.77903962, 0.22096038],
       [0.46507358, 0.53492642],
       [0.77546993, 0.22453007],
       [0.25610763, 0.74389237],
       [0.59670727, 0.40329273],
       [0.39698373, 0.60301627],
       [0.78656024, 0.21343976],
       [0.54516654, 0.45483346],
       [0.7596912 , 0.2403088 ],
       [0.5611569 , 0.4388431 ],
       [0.17377065, 0.82622935],
       [0.42142868, 0.57857132],
       [0.30538941, 0.69461059],
       [0.71221976, 0.28778024],
       [0.77790972, 0.22209028],
       [0.7938926 , 0.2061074 ],
       [0.42422877, 0.57577123],
       [0.63561337, 0.36438663],
       [0.33103371, 0.66896629],
       [0.72871439, 0.27128561],
       [0.16665264, 0.83334736],
       [0.56600768, 0.43399232],
       [0.11399337, 0.88600663],
       [0.76603645, 0.23396355],
       [0.62829315, 0.37170685],
       [0.61790495, 0.38209505],
       [0.30203861, 0.69796139],
       [0.34090197, 0.65909803],
       [0.70607803, 0.29392197],
       [0.20313854, 0.79686146],
       [0.79043907, 0.20956093],
       [0.7300077 , 0.2699923 ],
       [0.89600113, 0.10399887],
       [0.77546993, 0.22453007],
       [0.26055756, 0.73944244],
       [0.69918168, 0.30081832],
       [0.77546993, 0.22453007],
       [0.67311234, 0.32688766],
       [0.09662446, 0.90337554],
       [0.54254271, 0.45745729],
       [0.40002753, 0.59997247],
       [0.77903962, 0.22096038],
       [0.22136985, 0.77863015],
       [0.27141023, 0.72858977],
       [0.25655446, 0.74344554],
       [0.32955172, 0.67044828],
       [0.75152292, 0.24847708],
       [0.91016537, 0.08983463],
       [0.76603645, 0.23396355],
       [0.24559275, 0.75440725],
       [0.5662996 , 0.4337004 ],
       [0.87737541, 0.12262459],
       [0.29308287, 0.70691713],
       [0.41634563, 0.58365437],
       [0.72586122, 0.27413878],
       [0.31683213, 0.68316787],
       [0.82638206, 0.17361794],
       [0.84738944, 0.15261056],
       [0.77133106, 0.22866894],
       [0.7300077 , 0.2699923 ],
       [0.74708659, 0.25291341],
       [0.14880137, 0.85119863],
       [0.70306858, 0.29693142],
       [0.23583473, 0.76416527],
       [0.75414044, 0.24585956],
       [0.7849557 , 0.2150443 ],
       [0.37899345, 0.62100655],
       [0.31683213, 0.68316787],
       [0.3009509 , 0.6990491 ],
       [0.25754083, 0.74245917],
       [0.55349928, 0.44650072],
       [0.52051622, 0.47948378],
       [0.72120075, 0.27879925],
       [0.14880137, 0.85119863],
       [0.22409477, 0.77590523],
       [0.85302259, 0.14697741],
       [0.91714155, 0.08285845],
       [0.09654353, 0.90345647],
       [0.3277294 , 0.6722706 ],
       [0.66009241, 0.33990759],
       [0.47609389, 0.52390611],
       [0.44001423, 0.55998577],
       [0.20887576, 0.79112424],
       [0.1783463 , 0.8216537 ],
       [0.45533557, 0.54466443],
       [0.6893534 , 0.3106466 ],
       [0.73863728, 0.26136272],
       [0.8399901 , 0.1600099 ],
       [0.19001459, 0.80998541],
       [0.54516654, 0.45483346],
       [0.77903962, 0.22096038],
       [0.65072406, 0.34927594],
       [0.78656024, 0.21343976],
       [0.88776978, 0.11223022],
       [0.25780614, 0.74219386],
       [0.69874615, 0.30125385],
       [0.3864439 , 0.6135561 ],
       [0.78656024, 0.21343976],
       [0.70306858, 0.29693142],
       [0.65072406, 0.34927594],
       [0.73284787, 0.26715213],
       [0.47609389, 0.52390611],
       [0.53930442, 0.46069558],
       [0.68979648, 0.31020352],
       [0.75414044, 0.24585956],
       [0.54254271, 0.45745729]])

In [60]:
predicted_proba.shape

(140, 2)

In [64]:
###prob of getting 1 indicating absenteesim
predicted_proba[:,1]

array([0.28778024, 0.41239991, 0.55662562, 0.22096038, 0.91541657,
       0.66896629, 0.70207504, 0.87043779, 0.21692179, 0.25291341,
       0.50485031, 0.77359703, 0.92969016, 0.26495948, 0.69466915,
       0.44964119, 0.44972574, 0.46069558, 0.59882226, 0.94679318,
       0.30125385, 0.22096038, 0.58365437, 0.58365437, 0.7587085 ,
       0.25682913, 0.48934806, 0.14296697, 0.80065765, 0.22096038,
       0.37028423, 0.68316787, 0.68825755, 0.52694241, 0.22096038,
       0.53492642, 0.22453007, 0.74389237, 0.40329273, 0.60301627,
       0.21343976, 0.45483346, 0.2403088 , 0.4388431 , 0.82622935,
       0.57857132, 0.69461059, 0.28778024, 0.22209028, 0.2061074 ,
       0.57577123, 0.36438663, 0.66896629, 0.27128561, 0.83334736,
       0.43399232, 0.88600663, 0.23396355, 0.37170685, 0.38209505,
       0.69796139, 0.65909803, 0.29392197, 0.79686146, 0.20956093,
       0.2699923 , 0.10399887, 0.22453007, 0.73944244, 0.30081832,
       0.22453007, 0.32688766, 0.90337554, 0.45745729, 0.59997247,
       0.22096038, 0.77863015, 0.72858977, 0.74344554, 0.67044828,
       0.24847708, 0.08983463, 0.23396355, 0.75440725, 0.4337004 ,
       0.12262459, 0.70691713, 0.58365437, 0.27413878, 0.68316787,
       0.17361794, 0.15261056, 0.22866894, 0.2699923 , 0.25291341,
       0.85119863, 0.29693142, 0.76416527, 0.24585956, 0.2150443 ,
       0.62100655, 0.68316787, 0.6990491 , 0.74245917, 0.44650072,
       0.47948378, 0.27879925, 0.85119863, 0.77590523, 0.14697741,
       0.08285845, 0.90345647, 0.6722706 , 0.33990759, 0.52390611,
       0.55998577, 0.79112424, 0.8216537 , 0.54466443, 0.3106466 ,
       0.26136272, 0.1600099 , 0.80998541, 0.45483346, 0.22096038,
       0.34927594, 0.21343976, 0.11223022, 0.74219386, 0.30125385,
       0.6135561 , 0.21343976, 0.29693142, 0.34927594, 0.26715213,
       0.52390611, 0.46069558, 0.31020352, 0.24585956, 0.45745729])

## SAVE THE MODEL

In [65]:
import pickle

In [66]:
with open('model','wb') as file:
    pickle.dump(reg,file)

In [67]:
with open('modeltraining','wb') as file:
    pickle.dump(absenteeism_scaler,file)